cmd: stack
args:
 - install
name: stack install
targets:
  cabal:
    cmd: cabal
    args:
      - install
    name: cabal
  force-reinstall:
    cmd: cabal
    args:
      - install
      - --force-reinstalls
    name: force-reinstall
  test:
    cmd: shake
    args:
      - -f
    name: test
