flags: {}
arch: i386, x86_64
os: windows, linux
system-ghc: true
allow-newer: true
packages:
 - '.'
extra-deps:
- MissingH-1.3.0.1
- eternal-0.1.3
- HUnit-1.3.1.1
- base-unicode-symbols-0.2.2.4
- hslogger-1.2.9
- mtl-2.2.1
- network-2.6.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.9
- random-1.1
- regex-compat-0.95.1
- utf8-string-1.0.1.1
- regex-base-0.93.2
- regex-posix-0.95.2
- text-1.2.2.1
resolver: ghc-7.10.3
